Connecting app with LocationIQ API
jkkostrzewski/zzpj-project pull request #10
Opened 2020-05-17 13:01 UTC by pzachacz

2020-05-17 13:08 UTC, jkkostrzewski requested changes

2020-05-17 13:08 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        UriComponents uri = UriComponentsBuilder.fromHttpUrl(restApiUrl + "search.php?key=" + key).queryParam("q", query).queryParam("format", format).build();
polecam ctrt + alt + l

2020-05-17 13:09 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        UriComponents uri = UriComponentsBuilder.fromHttpUrl(restApiUrl + "search.php?key=" + key).queryParam("q", query).queryParam("format", format).build();
jak musze przesuwać paskiem w bok żeby odczytać linijke to nie jestem szczęśliwy :(

2020-05-17 13:14 UTC, jkkostrzewski requested changes

2020-05-17 13:14 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +public class LocationIqRestRepository {
Imo to nie powinno mieć w nazwie Repository - nie przechowujesz tutaj nic.

2020-05-17 13:18 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        ResponseEntity<LocationDataResponse> forEntity = restTemplate.getForEntity(uri.encode().toUri(), LocationDataResponse.class);
Czy jest sens deklarować tu zmienną tylko po to żeby ją zwrócić linijke niżej? Po prostu pytam może to jakaś zasada clean code której nie znam.

2020-05-17 13:36 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +public class LocationIqRestRepository {
Jakiś lepszy pomysł na nazwę? Nazwałam tak bo jednak daje jakiś dostęp do danych.

2020-05-17 13:40 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        ResponseEntity<LocationDataResponse> forEntity = restTemplate.getForEntity(uri.encode().toUri(), LocationDataResponse.class);
Nie jest zwracane to samo, dla mnie tak jest czytelniej, ale mogę zmienić.

2020-05-17 13:52 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        ResponseEntity<LocationDataResponse> forEntity = restTemplate.getForEntity(uri.encode().toUri(), LocationDataResponse.class);
@paluszkiewiczB co o tym sądzisz?

2020-05-17 13:54 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +public class LocationIqRestRepository {
Co sądzisz o LocationIqRestAdapter?

2020-05-17 15:06 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        UriComponents uri = UriComponentsBuilder.fromHttpUrl(restApiUrl + "search.php?key=" + key).queryParam("q", query).queryParam("format", format).build();
> 
> 
> polecam ctrt + alt + l

Mam chyba coś inaczej ustawione w Intellij bo mi tego nie chce ładnie formatować

2020-05-17 15:08 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        UriComponents uri = UriComponentsBuilder.fromHttpUrl(restApiUrl + "search.php?key=" + key).queryParam("q", query).queryParam("format", format).build();
ctrl + shift + a -> wpisz "shortcuts" i wybierz Manage shortcuts -> w wyszukiwarce na górze wpisz reformat code i to będzie twój skrót

2020-05-17 15:11 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        UriComponents uri = UriComponentsBuilder.fromHttpUrl(restApiUrl + "search.php?key=" + key).queryParam("q", query).queryParam("format", format).build();
ewentualnie jeśli nadal nie formatuje, to musisz wejsc w opcje formattera i ustawić standardowy do tego projektu

2020-05-17 23:29 UTC, paluszkiewiczB reviewed
nazwy metod zaczynają się od "getLocationData" - jak dla mnie to mogłoby tego prefixu nie być i byłoby sporo mniej czytania

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public LocationDataResponse[] getLocationDataFromQuery(String query) {
czemu tablica? :o

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +                .queryParam("lat", lat).queryParam("lon", lon).queryParam("format", format).build();
`var httpUrl = restApiUrl + "reverse.php?key=" + key;`
`UriComponents uri = UriComponentsBuilder.fromHttpUrl(httpUrl)`
`.queryParam("lat", lat)`
` .queryParam("lon", lon)`
`.queryParam("format", format)`
              `.build();`
IMO dużo bardziej czytelne

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public SupermarketLocationDataResponse[] getLocationDataOfNearbySupermarkets(double lat, double lon, double radius) {
tu też tablica :v upierdliwie sie z nich streamy robi

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public RoutingLocationDataResponse getLocationDataOfFastestRouteBetweenCoordinates(double latStart, double lonStart,
a da sie miedzy adresami?

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +                .fromHttpUrl(restApiUrl + "directions/driving/" + buildCoordsString(latStart, lonStart, latEnd, lonEnd)
budowanie tego urla wywalilbym do zmiennej

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +                .getForEntity(uri.encode().toUri(), RoutingLocationDataResponse.class);
chyba wszedzie zmienna uri ma na sobie wywoływane .encode().toUri() - możesz to zrobić od razu przy definiowaniu jej

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/location/model/LocationDataResponse.java
> +    private String place_id;
dziwnie wygląda ta podłoga w nazwie :x no ale formatu odpowiedzi z API nie zmienimy XD

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/resources/application.yml
> +locationiq:
skoro chcemy używać .yml a nie .properties, to będę musiał w swoim PRze przed mergem to zmienić

2020-05-17 23:29 UTC, paluszkiewiczB commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
używasz gdzieś data-jpa?

2020-05-17 23:29 UTC, paluszkiewiczB commented on pom.xml
> +			<artifactId>spring-boot-starter-data-rest</artifactId>
i data-rest też

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +public class LocationIqRestRepository {
może po prostu LocationService?

2020-05-17 23:29 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public LocationIqRestRepository(@Value("${locationiq.rest-api.key}") String key,
te properties można wrzucić do jednego pliku (nie tego konfigurującego całą aplikację)

2020-05-17 23:38 UTC, paluszkiewiczB requested changes

2020-05-17 23:38 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        this.restTemplate = new RestTemplate();
tego na pewno można używać wiele razy do różnych requestów? nie zmienia się jego stan przy kolejnych żądaniach?

2020-05-17 23:40 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        this.restTemplate = new RestTemplate();
W dokumentacji https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/client/RestTemplate.html
jest notka, żeby używać innej klasy do resta

2020-05-18 07:35 UTC, pzachacz commented on pom.xml
> +			<artifactId>spring-boot-starter-data-jpa</artifactId>
to jest zmergowane z twojego żeby się odpalało

2020-05-18 07:38 UTC, pzachacz commented on pom.xml
> +			<artifactId>spring-boot-starter-data-rest</artifactId>
jak powyżej

2020-05-18 07:39 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +public class LocationIqRestRepository {
> może po prostu LocationService?

To jest to - nie wiem dlaczego o tym nie pomyślałem ;/

2020-05-18 07:41 UTC, jkkostrzewski commented
generalnie ja bym wrzucił wszystkie te klaski do jednego pakietu

2020-05-18 07:42 UTC, pzachacz commented on src/main/resources/application.yml
> +locationiq:
mi tak było wygodniej ale mogę się dopasować

2020-05-18 07:45 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        this.restTemplate = new RestTemplate();
podczas mojego testowania nie było problemów, ale mogę spróbować zamienić na tego WebClient

2020-05-18 07:49 UTC, paluszkiewiczB commented on src/main/resources/application.yml
> +locationiq:
jak dla mnie może być .yml :D zaraz zmienię u siebie

2020-05-18 07:49 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public RoutingLocationDataResponse getLocationDataOfFastestRouteBetweenCoordinates(double latStart, double lonStart,
niestety nie, zaraz jeszcze dodam opis co zwraca każda funkcja i jakie parametry przyjmuje

2020-05-18 07:54 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public LocationDataResponse[] getLocationDataFromQuery(String query) {
bo tu zwraca tablicę różnych lokalizacji, bo jak wpiszesz np. biedronka to różne biedronki będą, można ewentualnie owrapować ale nie wiem czy się opłaca tworzyć klasę dla tego

2020-05-18 07:57 UTC, jkkostrzewski commented
> generalnie ja bym wrzucił wszystkie te klaski do jednego pakietu

https://codeforfunandmoney.wordpress.com/2016/07/13/domain-driven-design-and-package-organization/

2020-05-18 07:58 UTC, jkkostrzewski commented
> > generalnie ja bym wrzucił wszystkie te klaski do jednego pakietu
> 
> https://codeforfunandmoney.wordpress.com/2016/07/13/domain-driven-design-and-package-organization/

a raczej to chciałem wrzucić http://www.javapractices.com/topic/TopicAction.do?Id=205

2020-05-18 08:09 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        ResponseEntity<LocationDataResponse> forEntity = restTemplate.getForEntity(uri.encode().toUri(), LocationDataResponse.class);
![image](https://user-images.githubusercontent.com/45603875/82189369-8ee1f480-98ef-11ea-8900-a37a1b9039c9.png)

vs

![image](https://user-images.githubusercontent.com/45603875/82189417-a3be8800-98ef-11ea-86b3-1f37957e0ca9.png)

2020-05-18 08:11 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        ResponseEntity<LocationDataResponse> forEntity = restTemplate.getForEntity(uri.encode().toUri(), LocationDataResponse.class);
czas na pisanie tej deklaracji można zaoszczędzić na granie w Gwenta Kappa

2020-05-18 08:13 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public RoutingLocationDataResponse getLocationDataOfFastestRouteBetweenCoordinates(double latStart, double lonStart,
ogólnie propsuje dłuższe nazwy zmiennych które wyjaśniają lepiej co robi funkcja ale tutaj to już polecieliśmy za daleko

2020-05-18 08:15 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public RoutingLocationDataResponse getLocationDataOfFastestRouteBetweenCoordinates(double latStart, double lonStart,
na pewno możesz usunąć LocationDataOf z nazwy - nad BeetweenCoordinates tez bym się zastanowił żeby usunąć

2020-05-18 08:20 UTC, pzachacz commented
> 
> 
> generalnie ja bym wrzucił wszystkie te klaski do jednego pakietu

2020-05-18 08:23 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        ResponseEntity<LocationDataResponse> forEntity = restTemplate.getForEntity(uri.encode().toUri(), LocationDataResponse.class);
jak dla mnie to ctrl+alt+n

2020-05-18 08:25 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        ResponseEntity<LocationDataResponse> forEntity = restTemplate.getForEntity(uri.encode().toUri(), LocationDataResponse.class);
albo zamiast twardego typu var, bo do "=" jest połowa Pana Tadeusza

2020-05-18 08:26 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +    public LocationDataResponse[] getLocationDataFromQuery(String query) {
no to całkiem sensownie, ale mogłoby zwracać Iterable, Collection, List czy Set, bo łatwiej się to obsługuje

2020-05-18 08:32 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/integration/locationiq/LocationIqRestRepository.java
> +        ResponseEntity<LocationDataResponse> forEntity = restTemplate.getForEntity(uri.encode().toUri(), LocationDataResponse.class);
> jak dla mnie to ctrl+alt+n

ale to jest piękne - dzienkuje ci pan Bartek nie znałem tego skrótu

2020-05-18 21:12 UTC, jkkostrzewski requested changes

2020-05-18 21:12 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/location/integration/LocationRestService.java
> +        return restTemplate.exchange(uri.encode()
Dlaczego tutaj nie ma getForEntity jak w innych funkcjach? Z logicznego punktu widzenia użycie exchange nie ma tu największego sensu bo nawet nie wysyłasz HTTPEntity tylko nulla.

2020-05-18 21:21 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/location/integration/LocationRestService.java
> +        return restTemplate.exchange(uri.encode()
ma sens jak chce listę obiektów nie array, a nie chcę robić dodatkowej klasy wrapującej

2020-05-18 21:24 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/location/integration/LocationRestService.java
> +        return restTemplate.exchange(uri.encode()
ok w takim razie spoko

2020-05-18 21:25 UTC, jkkostrzewski approved these changes
Jest git. Przypomnij się później żebyśmy Ci wysłali formatter bo wydaje mi sie że jakoś dziwnie ci zawija te funkcje.

2020-05-19 13:06 UTC, paluszkiewiczB approved these changes

2020-05-19 13:54 UTC, merged