Security
jkkostrzewski/zzpj-project pull request #13
Opened 2020-05-19 18:12 UTC by sebastianKazmierski

2020-05-19 18:22 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/auth/database/ApplicationUserRepository.java
> +public interface ApplicationUserRepository extends CrudRepository<ApplicationUserEntity, Long> {
Bartek u siebie użył JpaRepository, które defacto jest rozszerzeniem CrudRepository. Może warto to zmienić jeśli na przykład chciałbyś w przyszłości dołożyć filtrowanie przez Specification jakie ma Bartek.

2020-05-19 18:28 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtTokenVerifier.java
> +    protected void doFilterInternal(HttpServletRequest httpServletRequest,
Ta funkcja jest zdecydowanie za długa. Myślisz, że dało by się to jakoś rozbić na mniejsze funkcje?

2020-05-19 18:33 UTC, jkkostrzewski commented on src/main/resources/application.properties
> +application.jwt.secretKey=securesecuresecuresecuresecuresecuresecuresecure
Na masterze korzystamy z .yml do konfiguracji. Albo przenosimy to do .yml albo tamto do properties.

2020-05-19 18:42 UTC, jkkostrzewski requested changes

2020-05-19 18:42 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +public class JwtUsernameAndPasswordAuthenticationFilter extends UsernamePasswordAuthenticationFilter {
Dlaczego nie poprostu JwtAuthenticationFilter?

2020-05-19 18:42 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +            UserNameAndPasswordAuthenticationRequest authenticationRequest =
A tutaj AuthenticationRequest?

2020-05-19 18:42 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +
Nie potrzebujemy tego entera

2020-05-19 18:42 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +                .setExpiration(java.sql.Date.valueOf(LocalDate.now().plusDays(jwtConfig.getTokenExpirationAfterDays())))
z tej litanii można nawet metode wyodrębnić - i nie będę musiał koniecznie wtedy sprawdzać jaka część różańca tutaj jest i kod będzie bardziej testowalny :D

2020-05-19 18:48 UTC, jkkostrzewski requested changes

2020-05-19 18:48 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUser.java
> +public class ApplicationUser implements UserDetails {
Proponowałbym po prostu User

2020-05-19 18:51 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUser.java
> +public class ApplicationUser implements UserDetails {
W ogóle mógłbyś wytłumaczyć o co chodzi z tymi dwoma klasami Usera? Dlaczego tak to jest zrobione i dlaczego klasa ApplicationUserEntity nie zawiera obiektu klasy ApplicationUser? Bo powtarzasz tam 6 tych samych pól.

2020-05-19 19:29 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +public class JwtUsernameAndPasswordAuthenticationFilter extends UsernamePasswordAuthenticationFilter {
Taka nazwa wydaje mi się lepsza bo pokazuje ze uwierzytelnianie jest przeprowadzane wyjątkowo na podstawie loginu i hasla a nie tak jak zazwyczaj na podstawie tokenu

2020-05-19 19:31 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +            UserNameAndPasswordAuthenticationRequest authenticationRequest =
Tak jak wyżej

2020-05-19 19:38 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +public class JwtUsernameAndPasswordAuthenticationFilter extends UsernamePasswordAuthenticationFilter {
To może przynajmniej skrócić nazwe i zostawić JwtPasswordAuthenticationFilter? Myśle że można się prosto z tego domyślić że chodzi o standardowe logowanie, a nie musisz zwijać wywołania obiektu od razu po znaku równości jak tam niżej ;d

2020-05-19 19:39 UTC, paluszkiewiczB requested changes
Jeśli te dwa filtry dają możliwość uwierzytelnienia sie:
- tokenem
- loginem i hasłem tak, że nie trzeba drugi raz wysyłać tokenu

To spoko, a jak przy loginie w zwrocie leci token, który i tak trzeba wysłać w następnym requeście to drugi filtr nie ma sensu imo i można to zrobić normalnie endpointem.
Swoją drogą to nie wyobrażam sobie sytuacji w której aplikacja pozwala jednocześnie wysłać jakieś żądanie (np pokaż sklepy) i jednocześnie kazać się logować. Więc opcja z loginem i hasłem chyba jest zbędna?

2020-05-19 19:39 UTC, paluszkiewiczB commented on pom.xml
> +			<artifactId>jjwt-jackson</artifactId> <!-- or jjwt-gson if Gson is preferred -->
Komentarz chyba zbędny

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/ZzpjApplication.java
> +    public static void main(String[] args) {
Inny formatter

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUserDao.java
> +public interface ApplicationUserDao {
Po co jest ten interfejs?

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUserDaoService.java
> +        return applicationUserEntityOptional.map(ApplicationUserEntity::getApplicationUser);
Ja bym to in-lineował

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/database/ApplicationUserRepository.java
> +public interface ApplicationUserRepository extends CrudRepository<ApplicationUserEntity, Long> {
IMO lepiej dodać dopiero jak będzie potrzebne

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/configuration/ApplicationUserRole.java
> +    SHOP_OWNER(Sets.newHashSet(QUEUE_WRITE,SHOP_WRITE)),
Set.of() jest krótsze :v i niemutowalne

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtTokenVerifier.java
> +                    .map(m -> new SimpleGrantedAuthority(m.get("authority")))
Iterujesz po authorities, a zmienna w lambdzie nazywa się m
Tego Stringa wywalilbym do stałych, albo properties

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtTokenVerifier.java
> +            var authorities = (List<Map<String, String>>) body.get("authorities");
String do stałych albo properties

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +                .setExpiration(java.sql.Date.valueOf(LocalDate.now().plusDays(jwtConfig.getTokenExpirationAfterDays())))
Tak w sumie to czemu data wygaśnięcia ma format z java.sql a nie LocalDate?

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/UserService.java
> +    private void registerNewUserAccount(UserSignUp userSignUp, ApplicationUserRole applicationUserRole) throws UserAlreadyExistsException {
Zwykły użytkownik na pewno potrzebuje konta?

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/UserService.java
> +        Optional<ApplicationUserEntity> applicationUser = applicationUserRepository.findByUsername(userSignUp.getUsername());
Jak nie potrzebujesz encji to możesz uzysz .existsByUsername() i od razu masz boola

2020-05-19 19:39 UTC, paluszkiewiczB commented on src/test/groovy/com/zachaczcompany/zzpj/AplicationSpec.groovy
> +//import spock.lang.Specification
Czemu super test wykomentowałeś? :'(

2020-05-19 19:40 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtUsernameAndPasswordAuthenticationFilter.java
> +public class JwtUsernameAndPasswordAuthenticationFilter extends UsernamePasswordAuthenticationFilter {
Albo jeszcze mam inną propozycję: JwtCredentialsAuthentificationFilter

2020-05-19 20:09 UTC, paluszkiewiczB requested changes

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUser.java
> +public class ApplicationUser implements UserDetails {
no w sumie to ja też nie czaję XD

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUserDao.java
> +public interface ApplicationUserDao {
bo chyba tylko jedna klasa go implementuje

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/configuration/ApplicationSecurityConfig.java
> +                .addFilter(new JwtUsernameAndPasswordAuthenticationFilter(authenticationManager(), jwtConfig, secretKey))
to chyba jest mało wydajne - przy ważności tokenów 14 dni za każdym razem sprawdzasz czy ktoś nie loguje się hasłem.

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/configuration/ApplicationSecurityConfig.java
> +                .addFilterAfter(new JwtTokenVerifier(secretKey, jwtConfig), JwtUsernameAndPasswordAuthenticationFilter.class)
ten filtr nazywa się Verifier, ten wyżej ma kosmicznie długą nazwę i nazywa się Filter

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/configuration/ApplicationUserRole.java
> +                .map(permission -> new SimpleGrantedAuthority(permission.getPermission()))
można 
```
.map(Class::getPermission)
.map(SimpleGrantedAuthority::new)
```
ale nie nalegam

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtTokenVerifier.java
> +
dwa entery

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/UserNameAndPasswordAuthenticationRequest.java
> +public class UserNameAndPasswordAuthenticationRequest {
albo AuthenticationDTO

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/UserService.java
> +    public void registerNewOwner(UserSignUp userSignUp) throws UserAlreadyExistsException {
to new jest raczej zbedne. przewaznie nie rejestruje sie kogos dwa razy

2020-05-19 20:09 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/UserSignUp.java
> +public class UserSignUp {
przy uwierzytelnieniu klasa ma na koncu "Request", ta nie ma

2020-05-19 21:45 UTC, paluszkiewiczB requested changes
myslalem ze wjechało cos wiecej

2020-05-19 21:45 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/UserDaoService.java
> +public class UserDaoService implements UserDao {
w nazwie Service, oznaczone Repository :v niby działa tak samo, ale nie ma konsekwencji

2020-05-19 21:45 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/UserDaoService.java
> +@Repository("database")
ten kwalifikator na 99% nie jest potrzebny, bo nie istnieje inny Bean implementujący ten zbędny interfejs :v:

2020-05-19 21:45 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/UserDao.java
> +public interface UserDao {
nadal nie kminie sensu istnienia tego interfejsu XD skoro ma tylko jedną implementację, to chyba nie ma z tego żadnej korzyści

2020-05-19 21:45 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/UserDaoService.java
> +public class UserDaoService implements UserDao {
no i jakbyś nie miał interfejsu to mógłbyś tę klasę nazwać UserDao bez problemu

2020-05-19 21:45 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/UserService.java
> +    public UserService(@Qualifier("database") UserDao userDao) {
tu tez byś się pozbył kwalifikatora

2020-05-21 10:40 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUser.java
> +public class ApplicationUser implements UserDetails {
A to nie robi się tak że na innych klasach się pracuje w programie a inne zapisuje do bazy?
I jeszcze nie mogę tego Set<? extends GrantedAuthority> zapisać do bazy bo to jest interfejs ale w sumie to chyba dałoby się to w seterze i geterze zamieniać i w polu trzymać stringi.

2020-05-21 10:42 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUserDao.java
> +public interface ApplicationUserDao {
A jak przewiduje że w przyszłości ktoś napisze inna klasę do tego to robić interfejs czy nie?

2020-05-21 10:45 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/security/jwt/JwtTokenVerifier.java
> +            var authorities = (List<Map<String, String>>) body.get("authorities");
do pola w klasie?

2020-05-21 10:50 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUser.java
> +public class ApplicationUser implements UserDetails {
W programie na chillku możesz pracować na encjach. Dopiero jak zwracasz na endpoint jakiś obiekt to najlepiej zmapować go na DTO, żebyś przez przypadek nie udostępnił wrażliwych danych.

2020-05-21 11:08 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/security/configuration/ApplicationSecurityConfig.java
> +                .addFilter(new JwtUsernameAndPasswordAuthenticationFilter(authenticationManager(), jwtConfig, secretKey))
ale działa

2020-05-21 11:09 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/ZzpjApplication.java
> +    public static void main(String[] args) {
jak to teraz zmienić?

2020-05-21 11:21 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/ZzpjApplication.java
> +    public static void main(String[] args) {
Ctrl +shift + a -> formatter control

2020-05-21 11:21 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/ZzpjApplication.java
> +    public static void main(String[] args) {
Na konfie jest plik z formaterem

2020-05-21 11:22 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/security/auth/ApplicationUserDao.java
> +public interface ApplicationUserDao {
Ja bym nie robił

2020-05-21 11:57 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/auth/UserDao.java
> +        return userRepository.findByUsername(username).map(UserEntity::getApplicationUser);
Jaka jest idea tego mapowania na nowy obiekt? Przeciez jak wyciągasz to z bazy findBy to już masz obiekt tylko musisz go wyciągnąć z optionala? Czy ja tu czegoś nie rozumiem?

2020-05-21 11:59 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/security/auth/UserService.java
> +        return userDaoInterface
To co jest tutaj możesz już robić przy wyciąganiu Usera z bazy. Walisz findBy i optional ma też orElseThrow

2020-06-11 20:02 UTC, pzachacz approved these changes

2020-06-11 20:12 UTC, paluszkiewiczB approved these changes

2020-06-11 20:12 UTC, jkkostrzewski approved these changes
narazie ok ;v

2020-06-11 20:12 UTC, merged