Opinions added
jkkostrzewski/zzpj-project pull request #25
Opened 2020-06-13 08:56 UTC by pzachacz

2020-06-13 11:20 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionController.java
> +import org.springframework.web.bind.annotation.*;
importuj wszystko pojedynczo

2020-06-13 11:21 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/shops/Shop.java
> +import javax.persistence.*;
tu tez

2020-06-13 11:24 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/shops/Shop.java
> +    private List<Opinion> opinions = new ArrayList<>();
Zastanawiam się czy nie lepiej by było umieścić te opinie w ShopStats. Wtedy można byłoby je uwzględniać w statystykach prosto.

2020-06-13 11:29 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionRepository.java
> +    List<Opinion> findAll();
Jakie widzisz zastosowanie dla zwracania wszystkich opinii? Nie przychodzi mi na myśl sytuacja w której chciałbym pokazać klientowi opinie z kilku sklepów.

2020-06-13 11:35 UTC, jkkostrzewski requested changes
Sprawdz komentarze wyżej

2020-06-13 13:12 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionRepository.java
> +    List<Opinion> findAll();
Chyba z rozpędu poleciałam, poprawię.

2020-06-13 13:12 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/shops/Shop.java
> +    private List<Opinion> opinions = new ArrayList<>();
@paluszkiewiczB jak uważasz ?

2020-06-13 13:18 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/shops/Shop.java
> +import javax.persistence.*;
Intellij mi podmienił, taki dziwny case że jak sobie dodaje import dla @ElementCollection to mi robi *

2020-06-13 13:35 UTC, paluszkiewiczB requested changes
Do obgadania hehe

2020-06-13 13:35 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionController.java
> +    @GetMapping("/all")
all mogłoby być po prostu na /opinions

2020-06-13 13:35 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionController.java
> +    @DeleteMapping("/remove/{id}")
tego remove też bym się pozbył i wysyłał po prostu DELETE na /{id}

2020-06-13 13:35 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionController.java
> +    @PostMapping("/add")
to tez mogłoby lecieć na /opinions, nie ma innego POSTa na tym URLu

2020-06-13 13:35 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionController.java
> +    @GetMapping("/shopId/{shopId}")
/shopId/{shopId} można zastąpić ?shopId={shopId} (Request Param)
wygląda bardziej jak filtrowanie i łatwiej jest później rozbudować apkę o więcej filtrów.

2020-06-13 13:35 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionRepository.java
> +    List<Opinion> findAll();
findAll jest domyśnie zaimplementowane, więc nie trzeba go dopisywać :D chyba, że nie odpowiadało Ci to, że zwracane jest Iterable zamiast List, to spoko. Z Iterable nie da się bezpośrednio stworzyć Streama.

2020-06-13 13:35 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionService.java
> +        opinionRepository.findById(id).ifPresent(opinion -> shopFacade.findShopById(opinion.getShopId())
wydaje mi się, że wystarczy wywołać metodę opinionRepository.deleteById.
Nie jestem pewien czy to usunie opinię ze sklepu, ale to prawdopodobnie można rozwiązać adnotacją @CascadeType. 
Wtedy nie istniałoby ryzyko, że ktoś usunie opinie i zapomni zrobić tego manewru z fasadą

2020-06-13 13:35 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/Shop.java
> +    private List<Opinion> opinions = new ArrayList<>();
szczerze mówiąc to nie wiem czy jest sens rozdmuchiwać tak Shop. Nie zawsze będziemy używali tych opinii (prawdopodobnie rzadziej niż częściej XD), a jeśli zostawimy je pozagnieżdżane, to każde wyciągnięcie sklepu z bazy (np. żeby zaktualizować długość kolejki albo zmienić godziny otwarcia w sobotę) spowoduje załadowanie tysiąca opinii do obiektu, bo jeśli dobrze pamiętam, to @ElementCollection nie ładuje się Lazy.
Co powiecie na to, żeby to pojedyncza opinia trzymała referencję do Shop @ OneToOne(fetchType = LAZY) ?

2020-06-13 13:35 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/ShopFacade.java
> +    Shop findShopById(Long id) {
przy usuwaniu Opinii wywołujesz tę metodę i nie bierzesz pod uwagę wyjątku, który tu rzucasz :v IMO to jest nie do uratowania catchem, ale gdyby udało się załatwić usuwanie przez @CascadeType, to nie trzeba będzie niczego rzucać

2020-06-13 13:37 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionRepository.java
> +    List<Opinion> findAll();
dlatego wolałam List, ale w sumie rzeczywiście średnio przydatne wgl

2020-06-13 13:47 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/shops/Shop.java
> +    private List<Opinion> opinions = new ArrayList<>();
No ja też miałam taką rozkminę, w sumie to może mogło by tak być

2020-06-13 14:22 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/shops/Shop.java
> +import javax.persistence.*;
no dlatego sie zmienia ustawienia intellija zeby tak nie robił

2020-06-14 18:22 UTC, paluszkiewiczB approved these changes

2020-06-14 18:22 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionService.java
> +                  .ifPresent(shop -> opinionRepository
spora ta lambda

2020-06-14 18:23 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/shops/OpinionDto.java
> +    private Integer rate;
Nie chcesz tego ograniczyć jakąś adnotacją? Np Min(0) Max(6)

2020-06-14 18:27 UTC, jkkostrzewski approved these changes
gucci gang

2020-06-14 20:16 UTC, merged