Reports
jkkostrzewski/zzpj-project pull request #35
Opened 2020-06-15 19:11 UTC by sebastianKazmierski

2020-06-15 19:43 UTC, pzachacz commented on src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionRepository.java
> +    @Query(value = "from Opinion where shop.id=:shopId")
Nie wiem czy mi się dobrze kojarzy, że query ze zmiennymi są podatne na SQL injections, w OptionService jest metodka getByShopId ale teraz wejdzie pr ze zmianą jej zwracanego typu ale można dodać metodę która by zwracała shopFacade.findShopById(shopId).map(opinionRepository::findByShop).orElse(Collections.emptyList()). Co o tym myślisz ?

2020-06-15 19:44 UTC, paluszkiewiczB requested changes
IMO za dużo public, za mało private final.
no i try catchy bez obsługi jakoś tak dużo

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/FilesGenerator.java
> +            rfg
jak lambda jest taka długa, to na pewno zasługuje na osobną metodę ze względu na nazwanie operacji + czytelność

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/FilesGenerator.java
> +            rfg
tu też metodka wjeżdża jak Parowóz Tomek do tunelu czasoprzestrzennego

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/GlobalControllerExceptionHandler.java
> +public class GlobalControllerExceptionHandler {
na masterze jest już CommonExceptionHandler https://github.com/jkkostrzewski/zzpj-project/blob/master/src/main/java/com/zachaczcompany/zzpj/commons/CommonExceptionHandler.java
to chyba może być obsłużone razem z zachowaniem formatu wyjściowego

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/IRowBuilder.java
> +public interface IRowBuilder {
pienkne, wzruszajonce przecionżenie metod :+1:

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/PdfCreator.java
> +    private Document document;
pola mogą być final?

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/PdfCreator.java
> +        try {
Try.runnable chyba by siadło

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/PdfCreator.java
> +                .forEach(e -> {
to też bym wrzucił do metody

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/PdfCreator.java
> +            document.add(table);
tu chyba też Try.runnable

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/PdfCreator.java
> +            document.add(table);
i będzie jedna linijka

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/PdfCreator.java
> +            cell.setHorizontalAlignment(Element.ALIGN_CENTER);
te enumy można wyciągnąć do stałych w tej samej klasie

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/ReportTypesConvertConfig.java
> +        registry.addConverter(new StringToReportReportTypes());
to powtórzenie Report jest celowe?

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/ReportsGenerator.java
> +    ShopSearchRepository shopSearchRepository;
private final w obydwu polach

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/PdfCreator.java
> +    public PdfCreator() {
musi być publiczna?

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/ReportsGenerator.java
> +    ShopSearchRepository shopSearchRepository;
teraz każdy bean z pakietu może sobie "załtołajerować" ten generator i wstawić w runtime nulla w pola.
nie żebym planował dodać takiego feature, ale po dawać co taką możliwość XD

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/ReportsGenerator.java
> +    public byte[] getSearchStatistics(ReportTypes reportTypes, Long shopId) {
te wszystkie metody są wykorzystywane poza pakietem, że są publiczne?

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +    private final CellStyle stringCellStyle;
a tutaj jest kulturalne private final :+1:

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +    public RowBuilder addRow() {
na pewno publiczna?

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +    public final class RowBuilder implements IRowBuilder {
publiczna?

2020-06-15 19:44 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionRepository.java
> +    @Query(value = "from Opinion where shop.id=:shopId")
Spring Data samo z siebie tego nie zrobi? nazwa metody chyba jest zgodna z konwencja

2020-06-15 19:48 UTC, paluszkiewiczB commented on src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionRepository.java
> +    @Query(value = "from Opinion where shop.id=:shopId")
nie zauważyłem że to jest zagnieżdżona wartość. Teoretycznie można chyba zrobić findByOpinion_Shop_Id, ale słabo to wygląda

2020-06-15 23:42 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +    private final CellStyle stringCellStyle;
bo tutaj poleciało kopiuj wklej z pewnego gista ;dd

2020-06-15 23:46 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/reports/ReportsController.java
> +import org.springframework.web.bind.annotation.*;
ŁI ŁU ŁI ŁU WILDCARD IMPORT POLICE

2020-06-15 23:52 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +import org.apache.poi.ss.usermodel.*;
dziki import

2020-06-15 23:55 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +    public byte[] getReportBytes() {
Nie podoba mi się że ta metoda jest tutaj. Gdybyś miał ją na zewnątrz w serwisie to mógłbyś prosto owinąć ją Eitherem w Error i zwrócić na kontrolerze jakby coś po drodze się wysypało.

2020-06-16 00:03 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +    public byte[] getReportBytes() {
Chyba że jakiś common handler to obsługuje to mooooooże być

2020-06-16 16:10 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/reports/GlobalControllerExceptionHandler.java
> +public class GlobalControllerExceptionHandler {
przez ResponseEntityExceptionHandler na razie zostawiam to bez obsługi

2020-06-16 16:11 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/shops/domain/OpinionRepository.java
> +    @Query(value = "from Opinion where shop.id=:shopId")
zrobiłem z OpinionServiec jak Paula pisała

2020-06-16 16:12 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +    public RowBuilder addRow() {
ta metoda implementuje interfaca

2020-06-16 16:13 UTC, sebastianKazmierski commented on src/main/java/com/zachaczcompany/zzpj/reports/XlsxCreator.java
> +    public RowBuilder addRow() {
dodałem @Override

2020-06-16 17:48 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/reports/FilesGenerator.java
> +    private static void createShopSearchRow(ReportFileGenerator rfg, ShopSearch row) {
Mógłbyś tą prywatną metode wrzucić na koniec klasy. Teraz te publiczne czyta się ładnie jak książke ale musze patrzeć czy na pewno nie ma jeszcze jakieś publicznej metody między prywatnymi

2020-06-16 17:49 UTC, jkkostrzewski commented on src/main/java/com/zachaczcompany/zzpj/reports/ReportsController.java
> +    @GetMapping("/searchStatistics/{reportType}")
Nie nalegam, ale możesz dorzucić adnotacje swaggera przy okazji.

2020-06-16 17:51 UTC, jkkostrzewski approved these changes

2020-06-17 00:12 UTC, closed without merging